### ISSUE TITLE
Vue 3 support 

### ISSUE THREAD

**Issue by anish2690** [cmp-cc/vue-cookies#59]
Hey guys,
Is there is a plan regarding this plugin and Vue3?

**Comment by NMFES** [comment]
+1 to the question

**Comment by polinwei** [comment]
+1 same

**Comment by anish2690** [comment]
@polinwei https://github.com/anish2690/vue-cookie-next

**Comment by ruralcoder** [comment]
We don't need branch offs. So please upgrade to v3!

**Comment by gstamosbg** [comment]
anything about Vue 3.0?

**Comment by talelmishali** [comment]
Any update?

**Comment by LittleWhiteLoti** [comment]
It works in Vue 3.0.11 if you are willing to change a little bit of the code. The loading style of ES 2015 works fine but how it is installed is incorrect. We no long user the Vue.prototype. It is now Vue.config.globalProperties. Put the following in vue-cookie.js instead of the Vue.prototype.$cookies = this;

`
      Vue.prototype ? Vue.prototype.$cookies = this : Vue.config.globalProperties.$cookies = this;
`

**Comment by Dan-Gamin** [comment]
#73 Fixes this. Why hasn't it merged yet?

**Comment by cmp-cc** [comment]
1.8.0 release

support vue3

**Comment by Dan-Gamin** [comment]
Oh, nice.
